var students = [
    {
        "name": "Anuj",
        "dept": "B.Tech, Computer Science and Engineering",
        "hall": "E-110,HALL13",
        "home": "Jind, Haryana",
        "roll": "210166",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "anuj21@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Aman Agarwal",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "C-606,HALL12",
        "home": "DHANBAD, Jharkhand",
        "roll": "200097",
        "parent": "0",
        "child":["210166","210026","210718","210087","210929","210051"],
        "img": "logo.png",
        "mail": "amanag20@iitk.ac.in",
        "bg": "A+",
    },{
        "name": "Abhijeet Verma",
        "dept": "BS, Physics",
        "hall": "E-110, HALL13",
        "home": "BARABANKI, U.P.",
        "roll": "210026",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "abhiteet21@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Phad Rohan Vaijnath",
        "dept": "B.Tech, Electrical Engineering",
        "hall": "E-110, HALL13",
        "home": "Parli V, Maharashtra",
        "roll": "210718",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "rohanpv21@iitk.ac.in",
        "bg": "B+",
    },{
        "name": "Akhil Vishnu Naik",
        "dept": "B.Tech, Mechanical Engineering",
        "hall": "E-111, HALL13",
        "home": "Ponda, Goa",
        "roll": "210087",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "akhilvn21@iitk.ac.in",
        "bg": "Not Available",
    },{
        "name": "Sanyam Pasricha",
        "dept": "B.Tech, Mechanical Engineering",
        "hall": "E-111, HALL13",
        "home": "New Delhi, Delhi",
        "roll": "210929",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "sanyamp21@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Adarsh Sahu",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-111, HALL13",
        "home": "FATEHPUR, U.P.",
        "roll": "210051",
        "parent": "200097",
        "child":[],
        "img": "logo.png",
        "mail": "adarshs21@iitk.ac.in",
        "bg": "B+",
    },
    // Dummy students
    {
        "name": "Dummy 1",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1001",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 2",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1002",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 3",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1003",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 4",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1004",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 5",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1005",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 6",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1006",
        "parent": "1010",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 10",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1010",
        "parent": "1100",
        "child":["1001", "1002", "1003", "1004", "1005", "1006"],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 20",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1020",
        "parent": "1100",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Dummy 30",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1030",
        "parent": "1100",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Dummy 40",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1040",
        "parent": "1100",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Dummy 50",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1050",
        "parent": "1100",
        "child": [],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },{
        "name": "Dummy 60",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1060",
        "parent": "1100",
        "child":[],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
    {
        "name": "Dummy 100",
        "dept": "B.Tech, Material Science and Engineering",
        "hall": "E-110, HALL13",
        "home": "India",
        "roll": "1100",
        "parent": "0",
        "child":["1010", "1020", "1030", "1040", "1050", "1060"],
        "img": "logo.png",
        "mail": "dummy@iitk.ac.in",
        "bg": "O+",
    },
];
function find_student_by_roll(r){
    for(let i=0; i<students.length; i++){
        if (students[i].roll== r){
            return students[i];
        }
    }
    return null;
}
